app/bank/bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('card/', include('cards.urls')),
    path('', include('users.urls'))
]

app/bank/cards/urls.py
from django.urls import path
from cards.views import *

app_name = 'cards'
urlpatterns = [
    path('', register, name='register'),
]

app/bank/users/urls.py
from django.urls import path
from users.views import *

app_name = 'users'
urlpatterns = [
    path('', login, name='login'),
    path('sign-up/', create, name='create')
]

app/bank/cards/models.py
from django.db import models
from cards import STATES, TYPES
from users.models import AuthUser

from datetime import datetime
import uuid
import logging
# Create your models here.

logger = logging.getLogger('card_logger')


class Card(models.Model):
    user = models.ForeignKey(AuthUser, on_delete=models.CASCADE)
    state = models.CharField(max_length=50, choices=STATES, default='active')
    type = models.CharField(max_length=50, choices=TYPES)
    last4 = models.CharField(max_length=10)
    exp_month = models.IntegerField()
    exp_year = models.IntegerField()
    cvv = models.IntegerField(default=123)
    cardholder_name = models.CharField(max_length=100, null=True)
    balance = models.FloatField()

    # custom token generation (in actual case should be done by special API gateway)
    token = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)

    def withdraw_cash(self, amount):
        if amount < self.balance:
            self.balance -= amount
            logger.info("Amount is successfully withdrawn!")
        else:
            logger.error("Amount exceeds current balance!")
        self.save()

    def deposit_cash(self, amount):
        if self.is_valid:
            self.balance += amount
            self.save()
        else:
            logger.error("Card is ", self.state)

    def enable(self):
        if self.is_valid:
            self.state = 'active'
            self.save()
        else:
            logger.error("Card is ", self.state)

    def disable(self):
        self.state = 'inactive'
        self.save()

    def is_valid(self):
        now_year = datetime.now().year
        now_month = datetime.now().month
        exp_year = 2000 + self.exp_year
        if exp_year < now_year or \
                exp_year == now_year and self.exp_month < now_month:
            self.state = 'expired'
            self.save()
            return False
        else:
            return True

    @classmethod
    def register(self, user, name, number, exp_date, cvv):
        Card.objects.create(
            user=user,
            cardholder_name=name,
            last4=number[-4:],
            exp_month=exp_date[2:],
            exp_year=exp_date[-2:],
            cvv=cvv if int(cvv) else 123,
            balance=0.0,
            type='mastercard'
        )

    def __str__(self) -> str:
        return f"{self.user.user.email} - {self.type}"


class CardHistory(models.Model):
    card = models.ForeignKey(
        Card, on_delete=models.SET_NULL, related_name='card_history', null=True)
    saved_state = models.CharField(max_length=50, choices=STATES)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.card.user} - {self.saved_state}"

app/bank/users/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User

# Create your models here.


class AuthUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    reg_date = models.DateTimeField(auto_created=True, auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self) -> str:
        return f"{self.user.email} - {self.active}"

    class Meta:
        ordering = ["-reg_date"]


@receiver(post_save, sender=AuthUser)
def notify_account_create(sender, instance, created, **kwargs):
    if created:
        pass  # TODO: enable logging for successfull account creation

app/bank/cards/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from users.models import AuthUser
from cards.models import Card
# Create your views here.


def register(request):
    template = 'cards/main.html'
    user_request = request.POST
    if not request.user:
        return redirect(reverse('users:login'))
    auth_user = AuthUser.objects.filter(user=request.user).first()
    cards = Card.objects.filter(user=auth_user)
    context = {'cards': cards}

    if user_request and not user_request.get('deposit', None) and \
            not user_request.get('withdraw', None) and \
            not user_request.get('check', None):
        name = user_request.get('name', None)
        number = user_request.get('number', None)
        exp_date = user_request.get('exp_date', None)
        cvv = user_request.get('cvv', None)
        if name and number and exp_date:
            Card.register(auth_user, name, number, exp_date, cvv)
    else:
        actions(request)

    return render(request, template, context)


def actions(request):
    user_request = request.POST
    deposit = user_request.get('deposit', None)
    withdraw = user_request.get('withdraw', None)
    card = user_request.get('check', None)
    if user_request:
        if not card:
            messages.add_message(request, messages.INFO, "No card selected!")
        elif card and deposit and not withdraw:
            deposit_cash(deposit, card)
        elif card and withdraw and not deposit:
            withdraw_cash(withdraw, card)
        elif card and withdraw and deposit:
            messages.add_message(request, messages.INFO,
                                 "Cannot process both actions!")
        elif card and not deposit and not withdraw:
            messages.add_message(request, messages.INFO,
                                 "No input for Card actions!")
    return redirect(reverse('cards:register'))


def deposit_cash(amount, card):
    card_ = Card.objects.get(id=card)
    card_.deposit_cash(float(amount))


def withdraw_cash(amount, card):
    card_ = Card.objects.get(id=card)
    card_.withdraw_cash(float(amount))

app/bank/users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from users.models import AuthUser

# Create your views here.


def login(request):
    template = 'index.html'
    if request.method == "POST":
        email = request.POST.get("email", None)
        passwd = request.POST.get("passwd", None)
        user = authenticate(username="john", password="secret")
        if user is None:
            return redirect(reverse('cards:register'))

    return render(request, template)


def create(request):
    template = 'users/create.html'
    if request.method == "POST":
        uname = request.POST.get("name", None)
        email = request.POST.get("email", None)
        passwd = request.POST.get("passwd", None)
        user = User.objects.filter(username=uname).first()
        if not user:
            user = User()
            user.username = uname
            user.email = email
        user.set_password(passwd)
        user.save()
        auth_user = AuthUser.objects.create(user=user)
        if auth_user:
            return redirect(reverse('cards:register'))

    return render(request, template)

app/bank/templates/base.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">        
        {% comment %} <link rel="stylesheet" href="main.css"> {% endcomment %}
        <title>Small Banking</title>
    </head>

    <body>
        {% block content %}
        {% endblock %}
        
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    </body>

</html>

app/bank/templates/cards/display_cards.html
<style>
.card {
    position: relative;
    display: flex;
    width: 395px;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #23406f;
    background-clip: border-box;
    border: 1px solid #23406f;
    border-radius: 7px;
}

.light {
    color: #7d7979;
    font-size: 11px;
}
</style>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">
          {{ message }}
    </div>    
    {% endfor %}
</ul>

{% endif %}
<form method="POST">
{% csrf_token %}
   {% for card in cards %}
        <div class="d-flex justify-content-center container text-white mt-5">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" name="check" value="{{card.id}}">    
                </div>
                <div class="card p-2 px-3 py-3">
                    <div class="d-flex justify-content-between align-items-center"><img src="https://i.imgur.com/8ANWXql.png" width="20" height="20">Balance: {{card.balance}}</div>
                    <div class="mt-3"><span class="mr-3">****</span><span class="mr-3">****</span><span class="mr-3">****</span><span class="mr-2">{{card.last4}}</span></div>
                    <div class="d-flex justify-content-between card-details mt-3 mb-3">
                        <div class="d-flex flex-column"><span class="light">Card Holder</span><span>{{card.cardholder_name}}</span></div>
                        <div class="d-flex flex-row">
                            <div class="d-flex flex-column mr-3"><span class="light">Expired</span><span>{{card.exp_month}}/{{card.exp_year}}</span></div>
                            <div class="d-flex flex-column"><span class="light">CVV</span><span>{{card.cvv}}</span></div>
                        </div>
                    </div>
                </div>
                
            </div>

    {% endfor %} 


    <div class="row w-50 ml-5 mt-3">
        <div class="form-group">
            <input type="number" class="form-control" name="deposit" placeholder="Deposit amount">       
        </div>         
    </div>
    <div class="row w-50 ml-5">
        <div class="form-group">
            <input type="number" class="form-control" name="withdraw" placeholder="Withdraw amount">       
        </div>
    </div>
    <div class="row ml-5">    
    <button type="submit" class="btn btn-primary">Send</button>
       
    </div>

</form>

app/bank/templates/cards/main.html
{% extends 'base.html' %}
{% block content %}

<div class="container p-3" >
    <h2 class="text-center">Mini Banking Playground</h1>
    <div class="row">
    <div class="col col-lg-6 p-5">
      <p class="text-center">Register Your Card<p>
      
      {% include "cards/register_form.html" %}  
    </div>
    <div class="col col-lg-6 p-5">
      {% include "cards/display_cards.html" %}
    </div>    
  </div>
</div>
{% endblock %}

app/bank/templates/cards/register_form.html
<form method="POST">
{% csrf_token %}
<div class="form-group">    
    <input type="text" class="form-control" name="name" aria-describedby="name" placeholder="Card holder name">   
  </div>
  <div class="form-group">    
    <input type="text" class="form-control" name="number" aria-describedby="number" placeholder="Card number (16 digits, no space)">   
  </div>
  <div class="form-group">    
    <input type="text" class="form-control" name="exp_date" placeholder="Expired date (MMYY)">
  </div>
  <div class="form-group">    
    <input type="number" class="form-control" name="cvv" placeholder="CVC (3 digits)">
  </div>  
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

app/bank/templates/index.html
{% extends 'base.html' %}
{% block content %}

<div class="container p-3" >   
  
      {% include "users/login.html" %}  
    
    
  </div>
</div>
{% endblock %}

app/bank/templates/users/create.html
{% extends 'base.html' %}
{% block content %}
<section class="vh-100 gradient-custom">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 class="fw-bold mb-2">Create Account</h2>
              <p class="mb-5">Please register your login and password!</p>
            <form method="POST">
            {% csrf_token %}
            
             <div class="form-outline form-white mb-4">
                <input type="text" id="typeNameX" class="form-control form-control-sm" placeholder="username (full name)" name="name" />                
              </div>

              <div class="form-outline form-white mb-4">
                <input type="email" id="typeEmailX" class="form-control form-control-sm" placeholder="email" name="email" />                
              </div>

              <div class="form-outline form-white mb-4">
                <input type="password" id="typePasswordX" class="form-control form-control-sm" placeholder="password" name="passwd"/>                
              </div>
              <button class="btn btn-outline-dark btn-sm " type="submit">Sign Up</button>
            </div>
            </form>            
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/bank/templates/users/login.html
<section class="vh-100 gradient-custom">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 class="fw-bold mb-2">Login</h2>
              <p class="mb-5">Please enter your login and password!</p>
            <form method="POST">
            {% csrf_token %}
              <div class="form-outline form-white mb-4">
                <input type="email" id="typeEmailX" class="form-control form-control-sm" placeholder="email" name="email" />                
              </div>

              <div class="form-outline form-white mb-4">
                <input type="password" id="typePasswordX" class="form-control form-control-sm" placeholder="password" name="passwd"/>                
              </div>
              <button class="btn btn-outline-dark btn-sm " type="submit">Login</button>
            </div>
            </form>
            <div>
              <p class="mb-0">Don't have an account? <a href="{% url 'users:create' %}" class="fw-bold">Sign Up</a>
              </p>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>